apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
  namespace: camunda-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda
          image: camunda/camunda-bpm-platform:7.20.0
          imagePullPolicy: IfNotPresent
          env:
            - name: CAMUNDA_JAVA_OPTS
              value: "-Xmx1024m -XX:+UseG1GC"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.h2.Driver"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
